development:
  adapter: postgresql
  encoding: utf8
  database: gelic
  pool: 5
  username: postgres
  password: gelicgelic
  host: 127.0.0.1

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: gelic
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: gelic
  pool: 5
  username: 
  password:

cucumber:
  <<: *TEST